# Generated by Django 3.1.7 on 2021-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField()),
                ('meat', models.CharField(choices=[('c', 'chicken'), ('b', 'beef'), ('m', 'mutton'), ('p', 'pork'), ('f', 'fish')], max_length=1)),
            ],
        ),
    ]
