# Generated by Django 3.1.7 on 2021-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210306_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.TextField(default='beef', max_length=10),
            preserve_default=False,
        ),
    ]
