# Generated by Django 3.1.7 on 2021-03-06 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_imagemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('address', models.TextField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state', models.TextField(max_length=20)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
