# Generated by Django 3.1.7 on 2021-03-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210306_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_item',
            new_name='CartItem',
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='home.product')),
            ],
        ),
    ]
